<option value="Art Education">Art Education</option>
<option value="Biological Sciences">Biological Sciences</option>
<option value="Biology">Biology</option>
<option value="Chemistry">Chemistry</option>
<option value="Early Childhood Education">Early Childhood Education</option>
<option value="Educational Media/Technology">Educational Media/Technology</option>
<option value="English">English</option>
<option value="Environmental Planning (for teachers)">Environmental Planning (for teachers)</option>
<option value="Filipino">Filipino</option>
<option value="Health Education">Health Education</option>
<option value="Human Kinetics">Human Kinetics</option>
<option value="Islamic Studies">Islamic Studies</option>
<option value="MAPEH">MAPEH</option>
<option value="Mathematics">Mathematics</option>
<option value="Music Education">Music Education</option>
<option value="Physical Education and Sports Science">Physical Education and Sports Science</option>
<option value="Physical Education Major in School PE">Physical Education Major in School PE</option>
<option value="Physical Sciences">Physical Sciences</option>
<option value="Physics">Physics</option>
<option value="Preschool Education">Preschool Education</option>
<option value="Reading">Reading</option>
<option value="Science">Science</option>
<option value="Social Studies">Social Studies</option>
<option value="Special Education (SPED)">Special Education (SPED)</option>
<option value="Technology and Livelihood Education">Technology and Livelihood Education</option>
<option value="Values Education">Values Education</option>