<option value="Accountancy">Accountancy</option>
<option value="Accounting Technology">Accounting Technology</option>
<option value="Aeronautical Engineering">Aeronautical Engineering</option>
<option value="Agribusiness/Management">Agribusiness/Management</option>
<option value="Agricultural Economics">Agricultural Economics</option>
<option value="Agricultural Engineering">Agricultural Engineering</option>
<option value="Agricultural Entrepreneurship">Agricultural Entrepreneurship</option>
<option value="Agricultural Technology">Agricultural Technology</option>
<option value="Agriculture">Agriculture</option>
<option value="Agro-Forestry">Agro-Forestry</option>
<option value="Animation">Animation</option>
<option value="Applied Mathematics">Applied Mathematics</option>
<option value="Applied Physics">Applied Physics</option>
<option value="Architecture">Architecture</option>
<option value="Atmospheric Science">Atmospheric Science</option>
<option value="Bio Chemical Engineering">Bio Chemical Engineering</option>
<option value="Biology">Biology</option>
<option value="Biomedical Engineering">Biomedical Engineering</option>
<option value="Business Admistration">Business Admistration</option>
<option value="Business Admistration in Business Economics">Business Admistration in Business Economics</option>
<option value="Business Admistration in Financial Management">Business Admistration in Financial Management</option>
<option value="Business Admistration in Human Resources Development">Business Admistration in Human Resources Development</option>
<option value="Business Admistration in Marketing Management">Business Admistration in Marketing Management</option>
<option value="Business Admistration in Operations Management">Business Admistration in Operations Management</option>
<option value="Ceramic Engineering">Ceramic Engineering</option>
<option value="Chemical Engineering">Chemical Engineering</option>
<option value="Chemistry">Chemistry</option>
<option value="Civil Engineering">Civil Engineering</option>
<option value="Communication Engineering">Communication Engineering</option>
<option value="Community Development">Community Development</option>
<option value="Computer Engineering">Computer Engineering</option>
<option value="Computer Science">Computer Science</option>
<option value="Criminology">Criminology</option>
<option value="Customs Administration">Customs Administration</option>
<option value="Development Communication">Development Communication</option>
<option value="Earth Science">Earth Science</option>
<option value="Economics">Economics</option>
<option value="Electrical Engineering">Electrical Engineering</option>
<option value="Electronics and Communications Engineering">Electronics and Communications Engineering</option>
<option value="Electronics Engineering">Electronics Engineering</option>
<option value="Entrepreneurship">Entrepreneurship</option>
<option value="Environmental Science">Environmental Science</option>
<option value="Fisheries">Fisheries</option>
<option value="Food Technology">Food Technology</option>
<option value="Foreign Service">Foreign Service</option>
<option value="Forensic Science">Forensic Science</option>
<option value="Forestry">Forestry</option>
<option value="Geodetic Engineering">Geodetic Engineering</option>
<option value="Geological Engineering">Geological Engineering</option>
<option value="Geology">Geology</option>
<option value="Guidance and Counseling">Guidance and Counseling</option>
<option value="Hotel and Restaurant Management">Hotel and Restaurant Management</option>
<option value="Human Development">Human Development</option>
<option value="Industrial Engineering">Industrial Engineering</option>
<option value="Information Systems">Information Systems</option>
<option value="Information Technology">Information Technology</option>
<option value="Interior Design">Interior Design</option>
<option value="International Studies">International Studies</option>
<option value="Marine Biology/Science">Marine Biology/Science</option>
<option value="Marine Engineering">Marine Engineering</option>
<option value="Marine Transportation">Marine Transportation</option>
<option value="Materials Engineering">Materials Engineering</option>
<option value="Mathematics">Mathematics</option>
<option value="Mechanical Engineering">Mechanical Engineering</option>
<option value="Medical Technology">Medical Technology</option>
<option value="Metallurgical/Mining Engineering">Metallurgical/Mining Engineering</option>
<option value="Meteorological Engineering">Meteorological Engineering</option>
<option value="Midwifery">Midwifery</option>
<option value="Mining Engineering">Mining Engineering</option>
<option value="Molecular Biology">Molecular Biology</option>
<option value="Multimedia">Multimedia</option>
<option value="Nursing">Nursing</option>
<option value="Nutrition">Nutrition</option>
<option value="Nutrition and Dietetics">Nutrition and Dietetics</option>
<option value="Occupational Therapy">Occupational Therapy</option>
<option value="Office Administration">Office Administration</option>
<option value="Petroleum Engineering">Petroleum Engineering</option>
<option value="Pharmacy">Pharmacy</option>
<option value="Philosophy">Philosophy</option>
<option value="Physical Therapy">Physical Therapy</option>
<option value="Physics">Physics</option>
<option value="Programming">Programming</option>
<option value="Psychology">Psychology</option>
<option value="Public Administration">Public Administration</option>
<option value="Public Safety">Public Safety</option>
<option value="Radiology Technology">Radiology Technology</option>
<option value="Real Estate Management">Real Estate Management</option>
<option value="Religious Education">Religious Education</option>
<option value="Respiratory Therapy">Respiratory Therapy</option>
<option value="Sanitary Engineering">Sanitary Engineering</option>
<option value="Social Work">Social Work</option>
<option value="Speech-Language Pathology">Speech-Language Pathology</option>
<option value="Sports Science">Sports Science</option>
<option value="Statistics/Applied Statistics">Statistics/Applied Statistics</option>
<option value="Theology">Theology</option>
<option value="Tourism Management"></option>
<option value="Veterinary Medicine">Veterinary Medicine</option>