<option value="Alabel">Alabel</option>
<option value="Antipolo City">Antipolo City</option>
<option value="Balanga City">Balanga City</option>
<option value="Baler">Baler</option>
<option value="Bangued">Bangued</option>
<option value="Basco">Basco</option>
<option value="Batangas City">Batangas City</option>
<option value="Bayombong">Bayombong</option>
<option value="Boac">Boac</option>
<option value="Bongao">Bongao</option>
<option value="Bontoc">Bontoc</option>
<option value="Borongan City">Borongan City</option>
<option value="Butuan City">Butuan City</option>
<option value="Cabarroguis">Cabarroguis</option>
<option value="Cagayan De Oro City">Cagayan De Oro City</option>
<option value="Calapan City">Calapan City</option>
<option value="Catarman">Catarman</option>
<option value="Catbalogan City">Catbalogan City</option>
<option value="Cebu City">Cebu City</option>
<option value="Daet">Daet</option>
<option value="Digos City">Digos City</option>
<option value="Dipolog City">Dipolog City</option>
<option value="Iba">Iba</option>
<option value="Ilagan City">Ilagan City</option>
<option value="Iloilo City">Iloilo City</option>
<option value="Ipil">Ipil</option>
<option value="Isabela City, Basilan">Isabela City, Basilan</option>
<option value="Isulan">Isulan</option>
<option value="Jolo">Jolo</option>
<option value="Jordan">Jordan</option>
<option value="Kabugao">Kabugao</option>
<option value="Kalibo">Kalibo</option>
<option value="Kidapawan City">Kidapawan City</option>
<option value="Koronadal City">Koronadal City</option>
<option value="La Trinidad">La Trinidad</option>
<option value="Lagawe">Lagawe</option>
<option value="Laoag City">Laoag City</option>
<option value="Legazpi City">Legazpi City</option>
<option value="Lingayen">Lingayen</option>
<option value="Lucena City">Lucena City</option>
<option value="Maasin City">Maasin City</option>
<option value="Malaybalay City">Malaybalay City</option>
<option value="Malita">Malita</option>
<option value="Malolos City">Malolos City</option>
<option value="Mambajao">Mambajao</option>
<option value="Mamburao">Mamburao</option>
<option value="Marawi City">Marawi City</option>
<option value="Masbate City">Masbate City</option>
<option value="Mati City">Mati City</option>
<option value="Nabunturan">Nabunturan</option>
<option value="Naval">Naval</option>
<option value="Oroquieta City">Oroquieta City</option>
<option value="Pagadian City">Pagadian City</option>
<option value="Palayan City">Palayan City</option>
<option value="Pili">Pili</option>
<option value="Prosperidad">Prosperidad</option>
<option value="Puerto Princesa City">Puerto Princesa City</option>
<option value="Romblon">Romblon</option>
<option value="Roxas City">Roxas City</option>
<option value="San Fernando City, La Union">San Fernando City, La Union</option>
<option value="San Fernando City, Pampanga">San Fernando City, Pampanga</option>
<option value="San Jose, Antique">San Jose, Antique</option>
<option value="San Jose, Dinagat Islands">San Jose, Dinagat Islands</option>
<option value="Santa Cruz, Laguna">Santa Cruz, Laguna</option>
<option value="Shariff Aguak (Maganoy)">Shariff Aguak (Maganoy)</option>
<option value="Siquijor">Siquijor</option>
<option value="Sorsogon City">Sorsogon City</option>
<option value="Surigao City">Surigao City</option>
<option value="Tabuk City">Tabuk City</option>
<option value="Tacloban City">Tacloban City</option>
<option value="Tagbilaran City">Tagbilaran City</option>
<option value="Tagum City">Tagum City</option>
<option value="Tandag City">Tandag City</option>
<option value="Tarlac City">Tarlac City</option>
<option value="Trece Martires City">Trece Martires City</option>
<option value="Tubod">Tubod</option>
<option value="Tuguegarao City">Tuguegarao City</option>
<option value="Vigan City">Vigan City</option>
<option value="Virac">Virac</option>