<option value="Binondo">Binondo</option>
<option value="Caloocan City">Caloocan City</option>
<option value="Ermita">Ermita</option>
<option value="Intramuros">Intramuros</option>
<option value="Las Piñas City">Las Piñas City</option>
<option value="Makati City">Makati City</option>
<option value="Malabon City">Malabon City</option>
<option value="Malate">Malate</option>
<option value="Mandaluyong City">Mandaluyong City</option>
<option value="Marikina City">Marikina City</option>
<option value="Muntinlupa City">Muntinlupa City</option>
<option value="Navotas City">Navotas City</option>
<option value="Paco">Paco</option>
<option value="Pandacan">Pandacan</option>
<option value="Parañaque City">Parañaque City</option>
<option value="Pasay City">Pasay City</option>
<option value="Pasig City">Pasig City</option>
<option value="Pateros">Pateros</option>
<option value="Port Area">Port Area</option>
<option value="Quezon City">Quezon City</option>
<option value="Quiapo">Quiapo</option>
<option value="Sampaloc">Sampaloc</option>
<option value="San Juan City">San Juan City</option>
<option value="San Miguel">San Miguel</option>
<option value="San Nicolas">San Nicolas</option>
<option value="Santa Ana">Santa Ana</option>
<option value="Santa Cruz, Manila">Santa Cruz, Manila</option>
<option value="Taguig City">Taguig City</option>
<option value="Tondo I / II">Tondo I / II</option>
<option value="Valenzuela City">Valenzuela City</option>