<option value="Amlan (Ayuquitan)">Amlan (Ayuquitan)</option>
<option value="Ayungon">Ayungon</option>
<option value="Bacolod City">Bacolod City</option>
<option value="Bacong">Bacong</option>
<option value="Bago City">Bago City</option>
<option value="Bais City">Bais City</option>
<option value="Basay">Basay</option>
<option value="Bayawan City (Tulong)">Bayawan City (Tulong)</option>
<option value="Binalbagan">Binalbagan</option>
<option value="Bindoy (Payabon)">Bindoy (Payabon)</option>
<option value="Cadiz City">Cadiz City</option>
<option value="Calatrava">Calatrava</option>
<option value="Candoni">Candoni</option>
<option value="Canlaon City">Canlaon City</option>
<option value="Cauayan">Cauayan</option>
<option value="Dauin">Dauin</option>
<option value="Dumaguete City">Dumaguete City</option>
<option value="Enrique B. Magalona (Saravia)">Enrique B. Magalona (Saravia)</option>
<option value="Escalante City">Escalante City</option>
<option value="Guihulngan City">Guihulngan City</option>
<option value="Himamaylan City">Himamaylan City</option>
<option value="Hinigaran">Hinigaran</option>
<option value="Hinoba-an (Asia)">Hinoba-an (Asia)</option>
<option value="Ilog">Ilog</option>
<option value="Isabela, Negros Occidental">Isabela, Negros Occidental</option>
<option value="Jimalalud">Jimalalud</option>
<option value="Kabankalan City">Kabankalan City</option>
<option value="La Carlota City">La Carlota City</option>
<option value="La Castellana">La Castellana</option>
<option value="La Libertad">La Libertad</option>
<option value="Mabinay">Mabinay</option>
<option value="Manapla">Manapla</option>
<option value="Manjuyod">Manjuyod</option>
<option value="Moises Padilla (Magallon)">Moises Padilla (Magallon)</option>
<option value="Murcia">Murcia</option>
<option value="Pamplona">Pamplona</option>
<option value="Pontevedra">Pontevedra</option>
<option value="Pulupandan">Pulupandan</option>
<option value="Sagay City">Sagay City</option>
<option value="Salvador Benedicto">Salvador Benedicto</option>
<option value="San Carlos City">San Carlos City</option>
<option value="San Enrique">San Enrique</option>
<option value="San Jose, Negros Oriental">San Jose, Negros Oriental</option>
<option value="Santa Catalina">Santa Catalina</option>
<option value="Siaton">Siaton</option>
<option value="Sibulan">Sibulan</option>
<option value="Silay City">Silay City</option>
<option value="Sipalay City">Sipalay City</option>
<option value="Talisay City">Talisay City</option>
<option value="Tanjay City">Tanjay City</option>
<option value="Tayasan">Tayasan</option>
<option value="Toboso">Toboso</option>
<option value="Valencia (Luzurriaga)">Valencia (Luzurriaga)</option>
<option value="Valladolid">Valladolid</option>
<option value="Vallehermoso">Vallehermoso</option>
<option value="Victorias City">Victorias City</option>
<option value="Zamboanguita">Zamboanguita</option>